EV-876 [FLUTTER] 11 - Teste de Widget
douglasWarren/everest-flutter-crypto pull request #11
Opened 2022-10-10 11:39 UTC by douglasWarren

## Realizado testes de widgets em todas a features do projeto
![Captura de tela 2022-10-10 081252](https://user-images.githubusercontent.com/113135354/194857924-5d38d979-2200-41fd-82e4-4837d4e2bea7.jpg)
![Captura de tela 2022-10-10 081051](https://user-images.githubusercontent.com/113135354/194857954-d65cabcc-d6bd-4fc1-9361-01ea294a19ba.jpg)

2022-10-10 12:03 UTC, carloscasanovad approved these changes

2022-10-10 12:03 UTC, carloscasanovad commented on test/presenter/ui/available/available_page_test.dart
> +  }
Dica: esta função pode ficar dentro do teu arquivo test_app_widget, para evitar coloca-ló em cada um dos testes.
Exemplo:
Future<void> loadPage(WidgetTester tester, Widget child) async {
  var availablePage = SetupWidgetTester(child: child);
  await tester.pumpWidget(availablePage);
}

2022-10-10 12:32 UTC, julialuciani approved these changes

2022-10-10 13:01 UTC, douglasWarren commented on test/presenter/ui/available/available_page_test.dart
> +  }
Refatorado conforme sugerido

2022-10-14 12:18 UTC, CarlosTSIlva requested changes

2022-10-14 12:18 UTC, CarlosTSIlva commented on lib/app/presenter/ui/conversion/widgets/to_coin_drop_list.dart
> +        : dropList[0];
dropList.first

2022-10-14 12:18 UTC, CarlosTSIlva commented on lib/core/app_routes.dart
> +//     (ref) => ref.watch(coinsWalletProvider).value!);
sempre revisar o código para tirar comentarios

2022-10-14 12:19 UTC, CarlosTSIlva commented
depois que corrigir me chama...

2022-10-14 12:43 UTC, douglasWarren commented on lib/app/presenter/ui/conversion/widgets/to_coin_drop_list.dart
> +        : dropList[0];
corrigido

2022-10-14 12:44 UTC, douglasWarren commented on lib/core/app_routes.dart
> +//     (ref) => ref.watch(coinsWalletProvider).value!);
corrigido

2022-10-14 12:54 UTC, douglasWarren commented
> depois que corrigir me chama...

corrigido

2022-10-14 12:56 UTC, CarlosTSIlva approved these changes

2022-10-14 12:57 UTC, merged